# Generated by Django 6.0.1 on 2026-02-12 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('method', models.CharField(choices=[('MANUAL', 'Manual'), ('FACE', 'Face Recognition')], help_text='How attendance was generated (Manual / Face Recognition)', max_length=10)),
                ('confirmed', models.BooleanField(default=False, help_text='Final confirmation by faculty')),
                ('marked_by', models.ForeignKey(limit_choices_to={'role': 'FACULTY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'unique_together': {('subject', 'date', 'section')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], max_length=10)),
                ('confidence_score', models.FloatField(blank=True, help_text='Face recognition confidence (0–1). Null for manual attendance.', null=True)),
                ('verified_by_faculty', models.BooleanField(default=False, help_text='Faculty has verified this record')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'unique_together': {('session', 'student')},
            },
        ),
    ]
