# Generated by Django 6.0.1 on 2026-02-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedialsession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remedialsession',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
