# Generated by Django 6.0.1 on 2026-02-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_section_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='capacity',
            field=models.IntegerField(default=60),
        ),
    ]
