# Generated by Django 6.0.1 on 2026-02-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='parent_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
